spring:
  redis:
    port: 6379
    host: 192.168.198.128
    password: 123456
    database: 0
    lettuce:
      pool:
        max-idle: 8
        max-active: 8
        min-idle: 1
        max-wait: 1000ms
